config/routes.rb
Euro2012ScoreSimulator::Application.routes.draw do

  root :to => 'groups#index'
  
  resources :teams

  resources :scores

  resources :groups

end

app/models/score.rb
class Score < ActiveRecord::Base
  belongs_to :home_team, :class_name => "Team"
  belongs_to :away_team, :class_name => "Team"
  belongs_to :group
  attr_accessible :home_team_id, :away_team_id, :a_score, :h_score, :group_id

  validates_numericality_of :a_score, :message => "is not a number"
  validates_numericality_of :h_score, :message => "is not a number"
  validates_inclusion_of :a_score, :in => 0..20, :message => "must be a number from 0 to 20"
  validates_inclusion_of :h_score, :in => 0..20, :message => "must be a number from 0 to 20"


  def against?(teams)
    teams = [teams] if teams.is_a?(Team)
    teams.inject(false) do |v, t|
      v ||= home_team == t || away_team == t
    end
  end

  def between?(teams)
    teams.include?(home_team) && teams.include?(away_team)
  end

  def draw?
    h_score == a_score
  end

  def goals_for(team)
    home_team == team ? h_score : a_score
  end

  def goals_ag(team)
    home_team == team ? a_score : h_score
  end

  def loss?(team)
    winner ? winner != team : false
  end

  def to_s
    "#@home_team #@h_score - #@a_score #@away_team"
  end

  def win?(team)
    winner ? winner == team : false
  end

  def winner
    h_score > a_score ? home_team : h_score < a_score ? away_team : nil
  end

  def ==(o)
    home_team.name == o.home_team.name and
    h_score == o.h_score and
    away_team.name == o.away_team.name and
    a_score == o.a_score
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  # GET /scores
  # GET /scores.json
  def index
    @groups = Group.all
    @scores = Score.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @scores }
    end
  end

  # GET /scores/1
  # GET /scores/1.json
  def show
    @score = Score.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @score }
    end
  end

  # GET /scores/new
  # GET /scores/new.json
  def new
    @score = Score.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @score }
    end
  end

  # GET /scores/1/edit
  def edit
    @score = Score.find(params[:id])
  end

  # POST /scores
  # POST /scores.json
  def create
    @score = Score.new(params[:score])

    respond_to do |format|
      if @score.save
        format.html { redirect_to @score.group, notice: 'Score was successfully created.' }
        format.json { render json: @score, status: :created, location: @score }
      else
        format.html { redirect_to @score.group, action: "new" }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /scores/1
  # PUT /scores/1.json
  def update
    @score = Score.find(params[:id])

    respond_to do |format|
      if @score.update_attributes(params[:score])
        format.html { redirect_to @score, notice: 'Score was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scores/1
  # DELETE /scores/1.json
  def destroy
    @score = Score.find(params[:id])
    group = @score.group
    @score.destroy

    respond_to do |format|
      format.html { redirect_to group_path(group) }
      format.json { head :no_content }
    end
  end
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/views/scores/_form.html.erb
<%= form_for(@score) do |f| %>
  <% if @score.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@score.errors.count, "error") %> prohibited this score from being saved:</h2>

      <ul>
      <% @score.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :home_team %><br />
    <%= f.text_field :home_team_id %>
  </div>
  <div class="field">
    <%= f.label :away_team %><br />
    <%= f.text_field :away_team_id %>
  </div>
  <div class="field">
    <%= f.label :h_score %><br />
    <%= f.number_field :h_score %>
  </div>
  <div class="field">
    <%= f.label :a_score %><br />
    <%= f.number_field :a_score %>
  </div>
  <div class="field">
    <%= f.label :group %><br />
    <%= f.text_field :group %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scores/edit.html.erb
<h2>Editing score</h2>

<%= render 'form' %>

<%= link_to 'Show', @score %> |
<%= link_to 'Back', scores_path %>

app/views/scores/index.html.erb
<div id="scores">
  <h2>Scores by group</h2>
<% @groups.each do |g| %>
  <% g_scores = @scores.select { |s| s.group == g } %>
  <div class="group_scores">
  <table>
    <%= link_to "Group #{g.name}", g %>
    <tr>
      <th>&nbsp;</th>
      <th class="center">Home</th>
      <th>&nbsp;</th>
      <th>&nbsp;</th>
      <th>&nbsp;</th>
      <th class="center">Away</th>
      <th>&nbsp;</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  <% g_scores.each do |score| %>
    <tr>
      <td><%= image_tag score.home_team.flag_img, { :height => 20, :width => 40, :class => "flag" } %></td>
      <td class="center"><%= score.home_team %></td>
      <td><%= score.h_score %></td>
      <td>&nbsp;vs&nbsp;</td>
      <td><%= score.a_score %></td>
      <td class="center"><%= score.away_team %></td>
      <td><%= image_tag score.away_team.flag_img, { :height => 20, :width => 40, :class => "flag" } %></td>
      <td><%= link_to 'Show', score %></td>
      <td><%= link_to 'Edit', edit_score_path(score) %></td>
      <td><%= link_to 'Delete', score, confirm: 'Are you sure?', method: :delete %></td>
    </tr>
  <% end %>
  </table>
  </div>
<% end %>
</div>

app/views/scores/new.html.erb
<h2>New score</h2>

<%= render 'form' %>

<%= link_to 'Back', scores_path %>

app/views/scores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Home:</b>
  <%= @score.home_team %>
</p>

<p>
  <b>Away:</b>
  <%= @score.away_team %>
</p>

<p>
  <b>H score:</b>
  <%= @score.h_score %>
</p>

<p>
  <b>A score:</b>
  <%= @score.a_score %>
</p>

<p>
  <b>Group:</b>
  <%= @score.group %>
</p>


<%= link_to 'Edit', edit_score_path(@score) %> |
<%= link_to 'Back', scores_path %>