config/routes.rb
Euro2012ScoreSimulator::Application.routes.draw do

  root :to => 'groups#index'
  
  resources :teams

  resources :scores

  resources :groups

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :teams
  has_many :scores

  attr_accessible :name, :scores

  def teams_with_points(n)
    teams.select { |t| t.points == n }
  end

  def scores_between(teams)
    scores.select { |s| s.between?(teams) }
  end

  def to_s
    name
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @groups }
    end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group = Group.find(params[:id])
    @groups = Group.all
    @score = Score.new(:group_id => @group.id)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/new
  # GET /groups/new.json
  def new
    @group = Group.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find(params[:id])
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(params[:group])

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render json: @group, status: :created, location: @group }
      else
        format.html { render action: "new" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.json
  def update
    @group = Group.find(params[:id])

    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h2>Editing group</h2>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<h2>Groups:</h2>

<div id="groups">
  <% @groups.each do |group| %>
    <div class="group">
      <div class="group_header"><%= link_to "Group #{group.name}", group %></div>
      <div class="group_content">
        <% group.teams.each do |team| %>
          <%= image_tag("#{team.name.downcase.gsub(" ", "_").gsub(".", "")}.gif",
            { :height => 40, :width => 80, :class => "flag" }) %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<!--<table>

<%# @groups.each do |group| %>
  <tr>
    <td><%# group.name %></td>
    <td><%# link_to 'Show', group %></td>
    <td><%# link_to 'Edit', edit_group_path(group) %></td>
    <td><%# link_to 'Destroy', group, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<%# end %>
</table>-->

<%# link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<h2>New group</h2>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<div class="nav">
  <%= link_to 'Groups', groups_path %>
  <% @groups.each do |group| %>
    <% if group.name == @group.name %>
      <%= @group.name %>
    <% else %>
      <%= link_to group.name, { :controller => "groups", :action => "show", :id => group.id } %>
    <% end %>
  <% end %>
</div>

<div class="main">
  <div class="score_table">
    <table class="board" summary="Group Board">
      <tr class="header">
        <th id="team">Group <%= @group.name %></th>
        <th>M</th>
        <th>W</th>
        <th>D</th>
        <th>L</th>
        <th>GF</th>
        <th>GA</th>
        <th>GD</th>
        <th>Pts</th>
      </tr>
      <% @group.teams.sort.each do |team| %>
      <tr class="<%= cycle('odd', 'even') %>">
        <% flag = image_tag team.flag_img, { :height => 20, :width => 40, :class => "flag" } %>
        <td id="team" ><%= flag %>&nbsp;<%=team.name %></td>
        <td><%= team.matches %></td>
        <td><%= team.wins %></td>
        <td><%= team.draws %></td>
        <td><%= team.losses %></td>
        <td><%= team.goals_for %></td>
        <td><%= team.goals_ag %></td>
        <td><%= team.goal_dif %></td>
        <td><%= team.points %></td>
      </tr>
      <% end %>
    </table>
  </div>

  <div class="box">
    <div class="box_header"><%= link_to "Scores", scores_path %></div>
    <div class="box_content">
      <table class="scores" summary="Score list">
        <% @group.scores.each do |s| %>
        <tr>
          <td class="home_team"><%= s.home_team %></td>
          <td><%= s.h_score %></td>
          <td>vs</td>
          <td><%= s.a_score %></td>
          <td class="away_team"><%= s.away_team %></td>
          <td class="remove">
            <%= link_to image_tag("remove_icon.png", { :width => 16, :height => 16 }),
              s, :method => :delete %>
          </td>
        </tr>
        <% end %>
      </table>
      <div id="all_scores_link"><%= link_to "See all groups", scores_path %></div>
    </div>
  </div>
</div>
<div id="score_form">
  <%= form_for(@score) do |f| %>
    <table>
      <tr class="header">
        <th>Group</th>
        <th>Home Team</th>
        <th>Score</th>
        <th>Score</th>
        <th>Away Team</th>
        <th>&nbsp;</th>
      </tr>
      <tr>
        <% groups = @groups.map { |g| [g.name, g.id] } %>
        <td><%= f.hidden_field :group_id, { :value => @group.id } %><%= @group.name %></td>
        <% group_teams = @group.teams.map { |t| [t.name, t.id] } %>
        <td><%= f.select :home_team_id, group_teams, :selected => group_teams[0] %></td>
        <td><%= f.number_field :h_score %></td>
        <td><%= f.number_field :a_score %></td>
        <td><%= f.select :away_team_id, group_teams, :selected => group_teams[1] %></td>
        <td><%= image_submit_tag "add_icon.png", { :width => 20, :height => 20 } %></td>
      </tr>
    </table>
  <% end %>
  <% if @score.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@score.errors.count, "error") %> prohibited this score from being saved:</h2>
       <ul>
      <% @score.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
    <p id="notice"><%= notice %></p>
  <% end %>
</div>